version: "3.7"

services:

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runsslserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.staging
