# Generated by Django 4.0.5 on 2022-06-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_contract_contract_file_contractfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractfile',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
