# Generated by Django 4.0.5 on 2022-06-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_apartmentphoto_apartmenthiddenphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='hidden_photo',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo',
        ),
    ]
