# Generated by Django 4.0.5 on 2022-06-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_apartment_hidden_photo_remove_apartment_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmenthiddenphoto',
            old_name='apartment',
            new_name='contract',
        ),
    ]
