# Generated by Django 4.0.5 on 2022-06-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rename_apartment_apartmenthiddenphoto_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentphoto',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_images', to='system.apartment'),
        ),
    ]
