# Generated by Django 4.0.5 on 2022-06-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
